# -*- coding: utf-8 -*-
"""Projeto Fase_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQ7Xmeoa2_9-uJXMAmPkPJ3iQBISmA9A
"""

"""Implemente um programa que leia, valide e analise dados informados pelo usuário. Os dados são meteorológicos e referem-se aos dados de 2021 (de janeiro a dezembro) registrados em uma cidade.

Toda entrada de dados deve ser validada. No caso de valor inválido, informe ao usuário o erro e permita que ele redigite o dado.

Seu programa deve coletar os seguintes dados:

• Mês: use valor numérico de 1 a 12 (janeiro a dezembro) para se referir aos meses do ano.

Para cada mês do ano, informe:
• Temperatura máxima do mês: devem estar em Celsius, garanta que estejam dentro de um intervalo válido para temperaturas, tal como: -60 graus à +50 graus.

A seguir, seu programa deve calcular e exibir:
• Temperatura média máxima anual: exibe a média das temperaturas máximas informadas.
• Quantidade de meses escaldantes: quantidade de meses com temperaturas máximas acima de 33 graus Celsius.
• Mês mais escaldante do ano: mês que registrou a maior temperatura máxima dentre todos os informados. O mês deve ser escrito na tela por extenso (janeiro a dezembro).
• Mês menos quente do ano: mês que registrou a menor temperatura máxima dentre todos os informados. O mês deve ser escrito na tela por extenso (janeiro a dezembro).

Observações gerais:

Use repetição para ler os dados e calcular as estatísticas solicitadas.
Não é necessário manter os dados lidos na memória após término do programa."""





#O meses serão mostrados em extenso para o usuario.

meses={1:"Janeiro",2:"Fevereiro",3:"Março",4:"Abril",5:"Maio",6:"Junho",7:"Julho",8:"Agosto",9:"Setembro",10:"Outubro",11:"Novembro",12:"Dezembro"}

# Laço principal: repete tudo do zero caso o usuário erre 3 vezes em algum mês
while True:
  temp=0   # Variável usada para armazenar a temperatura (inicializada com 0)
  maior_temp=-60
  menor_temp = 50
  soma_temp=0
  mes_maior="" #String Vazia deixa claro que essa variavel vai armazenar um texto
  mes_menor=""
  mes_max33=0

  erro = False                        # Esta variável controla se houve erro em algum mês

  for i in range(1, 13):               # i vai de 1 a 12, número do mês

    for tent in range(3):            # O usuário tem 3 tentativas para digitar a temperatura corretamente
      print("Digite a temperatura do Mês",i)
      temp = float(input())        # Lê o valor da temperatura com casas decimais

      if temp <-60 or temp > 50:  #se o valor estiver fora da margem aparece a mensagem repete a digitação
        print("Digite uma temperatura entre -60°C e 50°C")
        print()             # Linha em branco para visualização
      else:
        soma_temp += temp

        if temp>maior_temp:
          maior_temp=temp
          mes_maior=meses[i]

        if temp<menor_temp:
          menor_temp=temp
          mes_menor= meses[i]

        if temp>33:
          mes_max33 +=1


        break             #Sai do laço de tentativas se o valor estiver correto

    else:                   # Esse bloco executa se as 3 tentativas forem inválidas
      print(f"Você errou as três tentativas. {temp:}")
      print(f"Reiniciaremos tudo!. {temp:}")
      print()
      erro = True           # Indica que houve erro
      break                 # Sai do laço de meses para reiniciar tudo (Se não tiver esse Break ele continua aceitando valores erroneos)
  if erro==False:           # Se não houve erro em nenhum mês, encerramos o laço principal
    break

media_anual= soma_temp/12
#print("soma das temp",soma_temp)   teste para verificar a soma das temperaturas
print() #pular uma linha para melhor visualização
print(f"A Média anual de temperatura: {media_anual:.2f} °C")
print(f"O Mês com a maior temperatura foi: {mes_maior}, com {maior_temp}°C")
print(f"O Mês com a temperatura minima foi: {mes_menor}, com {menor_temp}°C")
print(f"Quantidade de meses escaldantes: {mes_max33}")